#include <iostream>
using namespace std;

int main()
{
	int x = 1, y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 2;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 3;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 4;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 5;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 6;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 7;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 8;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;

	x = 9;
	y = 1;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
	cout << x << "*" << y << "=" << x * y << endl;
	y++;
}